# Generated by Django 4.2.2 on 2023-07-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_holder_walletcashflow"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="name_stock",
            field=models.CharField(max_length=100),
        ),
    ]
